version: '3.9'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=t3st
      - MYSQL_PASSWORD=t3st
      - MYSQL_USER=user
      - MYSQL_DATABASE=mydb